"""Shared build-policy primitives for the Cores-spruce pipeline."""

from .admission import (
    COMMIT_BLACKLIST_PATH,
    COMMIT_BLACKLIST_POLICY_ID,
    commit_blacklist_reference_is_well_formed,
    golden_source_records,
    load_catalog_commit_blacklist,
    pin_source_records,
    require_catalog_cores_eligible,
    require_golden_sources_eligible,
    require_pin_sources_eligible,
    require_source_commits_eligible,
    source_commit_identity,
)
from .blacklist import (
    CommitBlacklist,
    CommitBlacklistEntry,
    CommitBlacklistError,
    CommitIdentity,
    CommitPolicyReport,
    commit_blacklist_content_sha256,
    load_commit_blacklist,
    parse_commit_blacklist,
    report_commit_policy,
    require_commit_eligible,
)

__all__ = [
    "COMMIT_BLACKLIST_PATH",
    "COMMIT_BLACKLIST_POLICY_ID",
    "CommitBlacklist",
    "CommitBlacklistEntry",
    "CommitBlacklistError",
    "CommitIdentity",
    "CommitPolicyReport",
    "commit_blacklist_reference_is_well_formed",
    "commit_blacklist_content_sha256",
    "golden_source_records",
    "load_catalog_commit_blacklist",
    "load_commit_blacklist",
    "parse_commit_blacklist",
    "pin_source_records",
    "report_commit_policy",
    "require_catalog_cores_eligible",
    "require_commit_eligible",
    "require_golden_sources_eligible",
    "require_pin_sources_eligible",
    "require_source_commits_eligible",
    "source_commit_identity",
]
