#!/usr/bin/env python3
"""Render the device x core compatibility matrix from captured evidence.

Reads the same model as ``device_sets.py`` (canonical compatibility manifests
joined against the device runtime contracts' captured library observations and
GLIBCXX ceilings) and renders it as a Markdown table, refreshing the block
between the markers in ``README.md``:

    <!-- device-matrix:start --> ... <!-- device-matrix:end -->

Legend (each cell is the *evidence-backed* verdict, never a guess):

  Y   eligible -- every DT_NEEDED library observed present, ceiling cleared
  C   over the device's captured GLIBCXX ceiling
  X   missing provider -- a needed library observed absent on the device
  ?   provider evidence uncaptured (device not probed, or library unobserved)
  -   no build for this device's ABI

Usage:
    python3 scripts/device_matrix.py            # print the Markdown table
    python3 scripts/device_matrix.py --write    # refresh the README block
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "device_sets", ROOT / "scripts" / "device_sets.py"
)
assert _spec is not None and _spec.loader is not None
device_sets = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(device_sets)

MARK_START = "<!-- device-matrix:start -->"
MARK_END = "<!-- device-matrix:end -->"

# Column order: probed devices first (arm64 then armhf), unprobed last.
DEVICE_COLUMNS = [
    ("device-trimui-a133p-family-v0", "Brick / TSP"),
    ("device-trimui-smart-pro-s-v0", "TSPS"),
    ("device-miyoo-flip-v0", "Flip"),
    ("device-gkd-pixel2-v0", "Pixel 2"),
    ("device-miyoo-a30-v0", "A30"),
    ("device-miyoo-mini-family-v0", "Mini +"),
    ("device-anbernic-h700-family-v0", "H700*"),
    ("device-magicx-zero28-v0", "Zero28*"),
]

BUCKET_SYMBOL = {
    "eligible": "Y",
    "eligible_ceiling_uncaptured": "?",
    "over_ceiling": "C",
    "missing_provider": "X",
    "provider_uncaptured": "?",
    "policy_excluded": "excl",
    "no_arch_target": "-",
}


def build_matrix() -> tuple[list[str], dict[str, dict[str, str]]]:
    report = device_sets.build_report()["devices"]
    cores: set[str] = set()
    cells: dict[str, dict[str, str]] = {}
    for contract_id, _label in DEVICE_COLUMNS:
        view = report[contract_id]
        for bucket, symbol in BUCKET_SYMBOL.items():
            for row in view.get(bucket, []):
                cores.add(row["core"])
                cells.setdefault(row["core"], {})[contract_id] = symbol
    return sorted(cores), cells


def render_markdown() -> str:
    cores, cells = build_matrix()
    lines = [
        "Evidence-backed per-device eligibility for every canonical core:",
        "`Y` eligible (all needed libraries observed present, ceiling cleared)"
        " - `C` over the captured GLIBCXX ceiling - `X` a needed library is"
        " absent on the device - `?` unverified (fails closed) - `-` no build"
        " for that ABI. Devices marked `*` have not been probed yet, so every"
        " C core there reports `?` rather than an assumed yes. Generated by"
        " `scripts/device_matrix.py --write`; regenerate after onboarding or"
        " a new device capture.",
        "",
        "<details><summary>Matrix: "
        f"{len(cores)} cores x {len(DEVICE_COLUMNS)} device families"
        "</summary>",
        "",
        "| core | " + " | ".join(label for _, label in DEVICE_COLUMNS) + " |",
        "|---" * (len(DEVICE_COLUMNS) + 1) + "|",
    ]
    for core in cores:
        row = [core]
        for contract_id, _label in DEVICE_COLUMNS:
            row.append(cells.get(core, {}).get(contract_id, "?"))
        lines.append("| " + " | ".join(row) + " |")
    lines += ["", "</details>"]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    block = render_markdown()
    if not args.write:
        print(block)
        return 0
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    if MARK_START not in text:
        print("error: README markers not found", file=sys.stderr)
        return 1
    head, rest = text.split(MARK_START, 1)
    _, tail = rest.split(MARK_END, 1)
    readme.write_text(
        head + MARK_START + "\n" + block + "\n" + MARK_END + tail,
        encoding="utf-8",
    )
    print(f"README matrix refreshed ({block.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
